/* Automatically generated by './build/bin/build-entry.js' */

import Button from './components/packages/button/index.js';
import Test from './components/packages/test/index.js';

const components = [
  Button,
  Test
];

const install = function(Vue, opts = {}) {
  /* istanbul ignore if */
  if (install.installed) return;

  components.map(component => {
    Vue.component(component.name, component);
  });
};

module.exports = {
  install,
  Button,
  Test
};

module.exports.default = module.exports;
