/* Automatically generated by './build/bin/build-entry.js' */

import Botton from './modules/button/index.js';

const components = [
  Botton
];

const install = function(Vue, opts = {}) {
  /* istanbul ignore if */
  if (install.installed) return;

  components.map(component => {
    Vue.component(component.name, component);
  });
};

module.exports = {
  install,
  Botton
};

module.exports.default = module.exports;
